version: '3.1'

services:
  bstreet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    networks:
      - homedock

networks:
  homedock:
    external: true
