version: '3.1'

services:

  www-bstreet:
    container_name: www-bstreet
    image: www-bstreet
    build: .
    ports:
        - "3000:3000"
    networks:
      - homedock

networks:
  homedock:
    external: true
